# Generated by Django 2.2.4 on 2021-02-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyToManyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
