# Generated by Django 2.2.4 on 2021-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvApp', '0002_auto_20210218_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
